% close all;
% set_param('SailingYachtModel/simple P heading controller/Kp', 'Value' , num2str(10));
% set_param('SailingYachtModel/simple P heading controller/Ki', 'Value' , num2str(2));
% angstring = strcat('[0;0;0;',num2str(deg2rad(0)), ';3;0;0;0]');
% set_param('SailingYachtModel/IC', 'Value' , angstring);
% set_param('SailingYachtModel/4DOF nonlinear sailing yacht model/vento', 'Value', num2str(deg2rad(180)));
% set_param('SailingYachtModel/controleTraj/distBord', 'Value' , num2str(50));
% set_param('SailingYachtModel/controleTraj/angBord', 'Value' , num2str(50));
% sim('SailingYachtModel');
close all;
hold on;
set(gca, 'FontSize', 14, 'LineWidth', 1);
p1 = plot(X.signals.values(:,1),X.signals.values(:,2),'r', 'LineWidth', 1);
% [l,c] = size(par.pontos_bordejar);
% pbstst = zeros(l,c+1);
% pbstst(:,2:c+1) = par.pontos_bordejar(:,1:c);
% [lpb, cpb] = size(pbstst);
% for contPlot = 2:cpb-1
%    plot(pbstst(1,contPlot), pbstst(2,contPlot),'blacko', 'LineWidth', 2); 
% end
p2 = plot(0,0, 'black.', 'MarkerSize', 32, 'LineWidth', 7.5);
p3 = plot(200,0, 'blackx', 'MarkerSize', 14, 'LineWidth', 2.5);
p4 = plot(100,100, 'blacko', 'MarkerSize', 11, 'LineWidth', 2.5);
plot(0,-70, 'black.', 'MarkerSize', 1, 'LineWidth', 0.1);
plot(0,130, 'black.', 'MarkerSize', 1, 'LineWidth', 0.1);
axis tight;
% [l,c] = size(X.time);
% tempos(i) = X.time(l,1);
grid;
xlabel('x[m]');
ylabel('y[m]');
legend([p1, p2, p3, p4],'Actual trajectory','P0', 'P1', 'P2');
% figure;
% [l,c] = size(X.time);
% lasttime = X.time(l,1);
% [l,c] = size(par.spvec);
% plot(0:lasttime/(c-1):lasttime,par.spvec);
% hold on;
% plot([0 lasttime], [1 1],'r');
% hold off;
