close all;
% figure;
% geoshow(10, 10);
% geoshow(40, 0);
% geoshow(-40, 0);
% geoshow(0,70);
% geoshow(0,-70);
subplot(2,2,[3 4])
geoshow(X.signals.values(:,2), X.signals.values(:,1));
hold on;
[l,c] = size(X.signals.values);
% plot(0,0);
% plot([0 0], [X.signals.values(1,2) X.signals.values(l,2)],'r');
[l,c] = size(par.pontos_bordejar);
pbstst = zeros(l,c+1);
pbstst(:,2:c+1) = par.pontos_bordejar(:,1:c);
plot(pbstst(1,:), pbstst(2,:),'r');
% figure;
% [l,c] = size(X.time);
% lasttime = X.time(l,1);
% [l,c] = size(par.spvec);
% plot(0:lasttime/(c-1):lasttime,par.spvec);
% hold on;
% plot([0 lasttime], [1 1],'r');
% plot(0,0);
% hold off;
% [l,c] = size(X.signals.values(:,1));
% pbstst = zeros(l,c+1);
% pbstst(:,2:c+1) = par.pontos_bordejar(:,1:c);
% plot([X.signals.values(1,1) X.signals.values(l,c)],[X.signals.values(1,1) X.signals.values(1,1)],'r');